services:
  ws-scylla-1: &scylla-main
    image: scylladb/scylla:6.0
    container_name: ws-scylla-1
    command: [ '--smp=1', '--memory=1GB', '--overprovisioned=1', '--developer-mode=1', '--seeds=ws-scylla-1' ]
    ports:
      - '9040:9042'
    networks:
      ws-scylla:
    volumes:
      - scylla-rust-1:/var/lib/scylla
  ws-scylla-2: &scylla-replica
    <<: *scylla-main
    container_name: ws-scylla-2
    ports:
      - '9041:9042'
    volumes:
      - scylla-rust-2:/var/lib/scylla
  ws-scylla-3:
    <<: *scylla-replica
    container_name: ws-scylla-3
    ports:
      - '9042:9042'
    volumes:
      - scylla-rust-3:/var/lib/scylla
volumes:
  scylla-rust-1:
    name: scylla-rust-1
  scylla-rust-2:
    name: scylla-rust-2
  scylla-rust-3:
    name: scylla-rust-3
networks:
  ws-scylla:
    name: ws-scylla
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.5.0/24
          gateway: 10.10.5.1
    driver_opts:
      com.docker.network.bridge.name: ws-scylla